# Generated by Django 4.1.2 on 2024-06-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobopage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
