# Generated by Django 4.1.2 on 2024-06-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobopage', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
    ]
