# Generated by Django 4.1.2 on 2024-06-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobopage', '0006_ordenes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordenes',
            new_name='Ordene',
        ),
    ]
