# Generated by Django 4.1.2 on 2024-06-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobopage', '0007_rename_ordenes_ordene'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordene',
            new_name='Orden',
        ),
    ]
